name: CI Build

on: push

jobs:
  build-tests:
    name: tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Zig 0.12.0
        run: curl -LO https://ziglang.org/download/0.12.0/zig-windows-x86_64-0.12.0.zip

      - name: Unzip Zig
        run: tar -xf zig-windows-x86_64-0.12.0.zip

      - name: Run the tests
        run: zig-windows-x86_64-0.12.0\zig.exe test -freference-trace src/main.zig
